import Head from 'next/head'
import Footer from '../components/main/footer'
import Hero from '../components/main/hero'
import Navbar from '../components/main/navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Footer />
    </div>
  )
}
