import Head from 'next/head'
import Footer from '../components/main/footer'
import Navbar from '../components/main/navbar'
import Projects from '../components/projects/projects';
function Main() {
    return (
        <div>
            <Head>
                <title>Choose one</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Projects />
            <Footer />
        </div>
    );
}

export default Main;