import Head from "next/head";
import Footer from "../../components/main/footer";
import Navbar from "../../components/main/navbar";
import OralCancer from "../../components/projects/oralCancer/oralCancer";

function Main() {
    return (
        <div>
            <Head>
                <title>Choose one</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <OralCancer />
            <Footer />
        </div>
    );
}

export default Main;